### ISSUE TITLE
Make it so bullets move towards cursor

### ISSUE THREAD

**Issue by BoxyUwU** [Supbscripter/GMTK-Jam#6]
When we spawn a bullet we should rotate it towards the cursors position.
We should also store a velocity in Bullet.cs when we instance a bullet prefab.
Once that is done in the Update() function inside of Bullet.cs we should be able to apply the velocity to the bullet. This should be done with Rigidbody.MovePosition or Rigidbody.Velocity but we don't have a Rigidbody component attached to bullets atm so we should just set transform.position manually.

**Comment by BlueFire561** [comment]
Bullet now rotates to the cursors position on start and moves in that direction at a speed,
Current speed set at 10. Can be changed in the bullet prefab.

**Comment by BlueFire561** [comment]
If you think this works and is good for now you can close the issue I just didnt want to just in case lol
