### ISSUE TITLE
Get enemies to not be stationary

### ISSUE THREAD

**Issue by BoxyUwU** [Supbscripter/GMTK-Jam#8]
We need the enemies to have some basic AI to go in a straight line towards the player. A basic implementation of this will probably be a bit buggy with them driving themselves straight into platforms and glitching out when ontop of the player, but that is gonna be fine because we need to solve Issue#7 before we can fix those 2 things. This stuff should all go in an 'EnemyAI' component that should be attached to the Enemy prefab.

You will have to figure out a way to have the EnemyAI component have a reference to the Player so it can find out what position the Player is at. You should be able to find the Player from the EnemyAI component with the [GameObject.Find() function](https://docs.unity3d.com/ScriptReference/GameObject.Find.html)

**Comment by BlueFire561** [comment]
> I would also like it if Enemies would totally bypass the platforms and have no physics interaction with them

So are the enemies going to at all be effected by the platforms or are they more like flying ghosts which can pathfind to the player?
